image: python:3.8.13-alpine3.15

stages:
  - test
  - linting

before_script:
  - python3 -V  # Print out python version for debugging
  - pip3 install -r requirements.txt
  - python3 main.py

linting:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - flake8 --ignore=E501,W503,F403,F405

test:
  script:
      - python3 -m unittest
