image: python:3.9-alpine3.14

stages:
  - test
  - linting

before_script:
  - python3 -V  # Print out python version for debugging

linting:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - flake8 --ignore=E501,F821,W503

test:
  script:
      - python3 -m unittest